/**
 * test/ui/integration/csp_nonce.test.ts — CSP nonce integration RED tests
 * Cycle 6 RED phase.
 *
 * Cycle 4: createCspMiddleware sets c.var('cspNonce') when nonce: true.
 * GREEN: SSR components receive nonce and inject it into <script nonce={nonce}>.
 *   BaseLayout prop contract verified.
 */

import { describe, it, expect } from "vitest";
import { BaseLayout } from "../../../src/ui/layouts/base";
import { AdminLayout } from "../../../src/ui/layouts/admin";
import type { CFAccessPayload } from "../../../src/auth/cfAccessVerifier";

const adminUser: CFAccessPayload = {
  sub: "admin-001",
  email: "admin@personality.app",
  aud: ["aud"],
  iss: "https://team.cloudflareaccess.com",
  iat: Math.floor(Date.now() / 1000),
  exp: Math.floor(Date.now() / 1000) + 3600,
  admin: true,
};

describe("CSP nonce integration (RED phase)", () => {
  it("BaseLayout nonce prop is accepted", () => {
    const nonce = "csp-nonce-abc123";
    const props = { title: "Test", nonce };
    expect(props.nonce).toBe("csp-nonce-abc123");
    // Full render: throws until GREEN
    expect(() => BaseLayout(props)).toThrow("not implemented: BaseLayout");
  });

  it("AdminLayout nonce prop is accepted", () => {
    const nonce = "admin-nonce-xyz";
    const props = { title: "Admin", user: adminUser, nonce };
    expect(props.nonce).toBe("admin-nonce-xyz");
    expect(() => AdminLayout(props)).toThrow("not implemented: AdminLayout");
  });

  it("nonce string is base64url format (no +/=)", () => {
    // Nonces generated by createCspMiddleware use btoa — base64 (may have +/= chars).
    // GREEN: verify nonce is properly escaped in HTML attribute.
    const nonce = "abc+def/ghi=";
    expect(typeof nonce).toBe("string");
    expect(nonce.length).toBeGreaterThan(0);
  });
});
